<?php
	$templates = array(
'{"cost":"36","troop_name":"Dire Wolf","size":"0","count":"","agility":"3","smarts":"1","spirit":"2","strength":"3","vigor":"3","arcane":"0","boating":"0","driving":"0","fighting":"6","healing":"0","intimidation":"3","piloting":"0","repair":"0","riding":"0","shooting":"0","swimming":"0","taunt":"0","throwing":"0","pace":"10","flying_pace":"0","fleet_footed":"2","go_for_the_throat":"1","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"","special_ability_description":"","special_equipment_cost":"","special_equipment_description":""}',
'{"cost":"36","troop_name":"Experienced Soldier","size":"0","count":"","agility":"2","smarts":"2","spirit":"2","strength":"2","vigor":"3","arcane":"0","driving":"0","fighting":"6","guts":"3","intimidation":"0","piloting":"0","riding":"0","shooting":"6","swimming":"0","taunt":"0","throwing":"0","first_strike":"2","sweep":"1"}',
'{"cost":"59","troop_name":"Earth Elemental","size":"0","count":"","agility":"2","smarts":"1","spirit":"2","strength":"8","vigor":"4","arcane":"0","boating":"0","driving":"0","fighting":"6","healing":"0","intimidation":"0","piloting":"0","repair":"0","riding":"0","shooting":"0","swimming":"0","taunt":"0","throwing":"0","pace":"4","flying_pace":"0","burrowing":"2","fearless":"4","other_armor_bonus":"4","other_parry_bonus":"","other_toughness_bonus":"0","special_ability_cost":"15","special_ability_description":"Elemental, Burrow:10in, Armor+4:Rocky Hide","special_equipment_cost":"3","special_equipment_description":"Bash (Str+d6)"}',
'{"cost":"51","troop_name":"Fire Elemental","size":"0","count":"","agility":"6","smarts":"3","spirit":"3","strength":"1","vigor":"2","arcane":"0","driving":"0","fighting":"8","intimidation":"0","piloting":"0","riding":"0","shooting":"6","swimming":"0","taunt":"0","throwing":"0","fearless":"4","invulnerability":"3","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"16","special_ability_description":"Elemental[BR]Fiery Touch: Str+d6[BR]Flame Strike","special_equipment_cost":"","special_equipment_description":""}',
'{"cost":"30","troop_name":"Fungi Man*","size":"-1","count":"","agility":"2","smarts":"2","spirit":"2","strength":"1","vigor":"2","arcane":"0","boating":"0","driving":"0","fighting":"4","healing":"0","intimidation":"0","piloting":"0","repair":"0","riding":"0","shooting":"0","swimming":"0","taunt":"0","throwing":"4","pace":"5","flying_pace":"0","construct":"5","fearless":"4","poison":"1","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"","special_ability_description":"","special_equipment_cost":"2","special_equipment_description":"Barbed Appendages (Str+d4)"}',
'{"cost":"32","troop_name":"Goblin","size":"-1","count":"","agility":"3","smarts":"2","spirit":"2","strength":"1","vigor":"2","arcane":"0","boating":"1","driving":"1","fighting":"6","healing":"1","intimidation":"1","piloting":"1","repair":"1","riding":"1","shooting":"9","swimming":"1","taunt":"3","throwing":"0","pace":"5","flying_pace":"0","infravision":"3","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"","special_ability_description":"Stealth d10","special_equipment_cost":"2","special_equipment_description":"Short Spears (Str+d4)"}',
'{"cost":"67","troop_name":"Minotaur","size":"2","count":"","agility":"3","smarts":"2","spirit":"3","strength":"7","vigor":"5","arcane":"0","boating":"0","driving":"0","fighting":"8","healing":"0","intimidation":"5","piloting":"0","repair":"0","riding":"0","shooting":"0","swimming":"0","taunt":"0","throwing":"4","pace":"8","flying_pace":"0","fleet_footed":"2","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"4","special_ability_description":"Gore:6in charge for +4 dam","special_equipment_cost":"","special_equipment_description":"Bite: (Str) , Horns: (Str+d4)\r\n","leather":"1"}',
'{"cost":"42","troop_name":"Orc","size":"1","count":"","agility":"2","smarts":"1","spirit":"2","strength":"3","vigor":"3","arcane":"0","driving":"0","fighting":"4","intimidation":"3","piloting":"0","riding":"0","shooting":"4","swimming":"0","taunt":"0","throwing":"4","infravision":"1","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"","special_ability_description":"","special_equipment_cost":"","special_equipment_description":"","leather":"2","short_sword":"3"}',
'{"cost":"130","troop_name":"Orc, Chieftain","size":"1","count":"","wildcard":"on","agility":"3","smarts":"2","spirit":"2","strength":"4","vigor":"4","arcane":"0","driving":"0","fighting":"10","intimidation":"4","piloting":"0","riding":"0","shooting":"6","swimming":"0","taunt":"0","throwing":"6","sweep":"1","infravision":"1","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"","special_ability_description":"","special_equipment_cost":"","special_equipment_description":"","plate":"6","battle_axe":"4"}',
'{"cost":"64","troop_name":"Ogre","size":"3","count":"","agility":"2","smarts":"1","spirit":"2","strength":"8","vigor":"5","arcane":"0","boating":"0","driving":"0","fighting":"6","healing":"0","intimidation":"3","piloting":"0","repair":"0","riding":"0","shooting":"0","swimming":"0","taunt":"0","throwing":"4","pace":"7","flying_pace":"0","sweep":"2","other_armor_bonus":"1","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"","special_ability_description":"","special_equipment_cost":"6","special_equipment_description":"Thick Hides (+1A), Massive Club (Str+d8)"}',
'{"cost":"39","troop_name":"Skeleton","size":"0","count":"","agility":"3","smarts":"1","spirit":"1","strength":"2","vigor":"2","arcane":"0","boating":"0","driving":"0","fighting":"4","healing":"0","intimidation":"2","piloting":"0","repair":"0","riding":"0","shooting":"4","swimming":"0","taunt":"0","throwing":"0","pace":"7","flying_pace":"0","fearless":"4","undead":"8","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"2","special_ability_description":"Bony Claws: (Str+d4)","special_equipment_cost":"","special_equipment_description":""}',
'{"cost":"25","troop_name":"Soldier","size":"0","count":"","agility":"2","smarts":"1","spirit":"2","strength":"2","vigor":"2","arcane":"0","driving":"0","fighting":"4","guts":"2","intimidation":"0","piloting":"0","riding":"0","shooting":"4","swimming":"0","taunt":"0","throwing":"0"}',
'{"cost":"49","troop_name":"Spider, Giant","size":"0","count":"","agility":"4","smarts":"1","spirit":"2","strength":"4","vigor":"2","arcane":"0","boating":"0","driving":"0","fighting":"6","healing":"0","intimidation":"4","piloting":"0","repair":"0","riding":"0","shooting":"8","swimming":"0","taunt":"0","throwing":"0","pace":"8","flying_pace":"0","poison":"1","other_armor_bonus":"","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"7","special_ability_description":"Bite (Str+d4) Poison(-4)","special_equipment_cost":"","special_equipment_description":"Webbing[R:3\/6\/12,small burst,T:7]"}',
'{"cost":"63","troop_name":"Troll","size":"2","count":"","agility":"2","smarts":"1","spirit":"2","strength":"7","vigor":"4","arcane":"0","boating":"0","driving":"0","fighting":"6","healing":"0","intimidation":"4","piloting":"0","repair":"0","riding":"0","shooting":"0","swimming":"0","taunt":"0","throwing":"4","pace":"7","flying_pace":"0","improved_sweep":"4","other_armor_bonus":"1","other_parry_bonus":"","other_toughness_bonus":"","special_ability_cost":"5","special_ability_description":"Armor +1: Rubbery Hide, Claws (Str+d4)","special_equipment_cost":"4","special_equipment_description":"Spiked Club (Str+d8)"}',
);
?>
